# ----------------------------
# DataSource
# ----------------------------
spring.datasource.url=jdbc:hsqldb:mem:game
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.hsqldb.jdbcDriver

# ----------------------------
# HikariCP
# ----------------------------
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000