<<<<<<< HEAD
spring.application.name=janken_game

#アプリケーションのポート番号
server.port=8080
=======
# ----------------------------
# Servlet / Encoding
# ----------------------------
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true
>>>>>>> refs/remotes/origin/develop

<<<<<<< HEAD
#HSQLDBデータベース設定
spring.datasource.url=jdbc:hsqldb:hsql://localhost/jankendb
spring.datasource.driverClassName=org.hsqldb.jdbc.JDBCDriver
spring.datasource.username=SS3
spring.datasource.password=ss3
spring.jpa.database-platform=org.hibernate.dialect.HSQLDialect

mybatis.type-aliases-package=entity
mybatis.mapper-locations=classpath:/mapper/**/*.xml
#スネークケースからキャメルケースに自動で調整
mybatis.configuration.map-underscore-to-camel-case=true

spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
=======
# ----------------------------
# DataSource
# ----------------------------
spring.datasource.url=jdbc:hsqldb:mem:game
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.hsqldb.jdbcDriver


# ----------------------------
# HikariCP
# ----------------------------
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000
>>>>>>> refs/remotes/origin/develop
