# ----------------------------
# Servlet / Encoding
# ----------------------------
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

# ----------------------------
# DataSource
# ----------------------------
spring.datasource.url=jdbc:hsqldb:hsql://localhost:9001/game
spring.datasource.username=LOCAL_USER
spring.datasource.password=password
spring.datasource.driver-class-name=org.hsqldb.jdbcDriver

# ----------------------------
# HikariCP
# ----------------------------
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000
