CREATE SCHEMA IF NOT EXISTS GAME;

CREATE TABLE GAME.MATCH_RESULT (
    MATCH_RESULT_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ATTACKER_ID BIGINT NOT NULL,
    DEFENDER_ID BIGINT NOT NULL,
    GAME_ID BIGINT NOT NULL,
    MATCH_DATETIME TIMESTAMP NOT NULL,
    JUDGE INTEGER NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    VERSION INTEGER NOT NULL,
    ATTACKER_DIRECTION INTEGER NOT NULL,
    DEFENDER_DIRECTION INTEGER NOT NULL
);

-- ユーザ ID 用のシーケンス
CREATE SEQUENCE seq_user_id START WITH 1;

-- ユーザ情報テーブル
CREATE TABLE IF NOT EXISTS user_information_tbl (
    user_id BIGINT GENERATED BY DEFAULT AS SEQUENCE seq_user_id PRIMARY KEY,
    user_name VARCHAR(100) NOT NULL UNIQUE,
    mail_address VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    status int NOT NULL,
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    version INT DEFAULT 1 NOT NULL
);

-- 履歴テーブル用シーケンス
CREATE SEQUENCE seq_history_id START WITH 1;

-- ゲームの種類マスタ
CREATE TABLE game_type_mst (
    game_type_id INT PRIMARY KEY,
    game_name VARCHAR(50) NOT NULL
);

INSERT INTO game_type_mst VALUES
(0, 'じゃんけん'),
(1, 'あっちむいてほい');

-- 結果の種類マスタ
CREATE TABLE result_mst (
    result_id INT PRIMARY KEY,
    result_name VARCHAR(20) NOT NULL
);

INSERT INTO result_mst VALUES
(0, '勝ち'),
(1, '負け'),
(2, 'あいこ');

-- ゲーム × 結果の組み合わせマスタ
CREATE TABLE game_result_mst (
    game_type_id INT NOT NULL,
    result_id INT NOT NULL,
    PRIMARY KEY (game_type_id, result_id),
    FOREIGN KEY (game_type_id) REFERENCES game_type_mst(game_type_id),
    FOREIGN KEY (result_id) REFERENCES result_mst(result_id)
);

INSERT INTO game_result_mst VALUES
(0,0),(0,1),(0,2),  -- じゃんけん
(1,0),(1,1);         -- あっちむいてほい


-- 履歴テーブル
CREATE TABLE result_history_tbl (
    history_id BIGINT GENERATED BY DEFAULT AS SEQUENCE seq_history_id PRIMARY KEY,
    user_id BIGINT NOT NULL,
    game_type_id INT NOT NULL,
    result_id INT NOT NULL,
    execute_datetime DATETIME NOT NULL,
    opponent BIGINT NOT NULL,
    user_choice VARCHAR(10),
    create_datetime DATETIME NOT NULL,
    update_datetime DATETIME NOT NULL,
    version INT NOT NULL,
    FOREIGN KEY (game_type_id, result_id)
        REFERENCES game_result_mst(game_type_id, result_id)
);

ALTER TABLE result_history_tbl ADD FOREIGN KEY (user_id) REFERENCES user_information_tbl(user_id);
ALTER TABLE result_history_tbl ADD FOREIGN KEY (opponent) REFERENCES user_information_tbl(user_id);

INSERT INTO user_information_tbl
(user_id, user_name, mail_address, password, status,
 create_datetime, update_datetime, version)
VALUES
(0, 'CPU', 'cpu@game.local', 'dummy', 1,
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);

