package jp.co.sfrontier.ss3.game.mapper;

import java.time.LocalDateTime;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import jp.co.sfrontier.ss3.game.dto.MatchResultRequest;
import jp.co.sfrontier.ss3.game.entity.MatchResult;
import jp.co.sfrontier.ss3.game.value.LookOverThereMatchHistory;

@Mapper
public interface MatchResultMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GAME.MATCH_RESULT
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	int insert(MatchResult row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GAME.MATCH_RESULT
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	int insertSelective(MatchResult row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GAME.MATCH_RESULT
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	MatchResult selectByPrimaryKey(Long matchResultId);

	/**
	 * プレイヤーの対戦履歴を取り出す<br>
	 * 対戦日の新しい順に取り出す
	 * @param attackerId アタッカーID
	 * @returnt 対戦結果が存在しない場合、空のリストを返す
	 */
	List<MatchResult> selectByAttackerId(@Param("attackerId") long attackerId, @Param("gameId") long gameId);

	/**
	 * 1日の最新対戦履歴を取得する<br>
	 * <br>
	 * @param fromDate 開始日
	 * @param toDate 終了日
	 * @param playerId プレイヤーID
	 * @return 1日の最新対戦履歴
	 */
	List<LookOverThereMatchHistory> selectRecentHistory(
			@Param("fromDate") LocalDateTime fromDate,
			@Param("toDate") LocalDateTime toDate,
			@Param("playerId") Long playerId);

	/**
	 * プレイヤーの全対戦履歴を取得する（全ゲーム共通）<br>
	 * 対戦日時の降順<br>
	 * <br>
	 * @param playerId プレイヤーID
	 * @return プレイヤーの全対戦履歴
	 */
	List<MatchResult> selectRecentHistoryAll(
			@Param("playerId") Long playerId);

	/**
	 * あっちむいてほいの表示確認用の簡易対戦履歴を取得する<br>
	 * <br>
	 */
	List<LookOverThereMatchHistory> selectHistory(
			@Param("playerId") Long playerId);

	/**
	 * 対戦履歴一覧を取得する。
	 *
	 * <p>
	 * 引数 gameTypeId が null の場合は
	 * ゲームタイプによる絞り込みを行わず、
	 * 全ゲーム種別の履歴を対象として取得する。
	 * </p>
	 *
	 * @param gameTypeId ゲームタイプID（null の場合は全件取得）
	 * @return 条件に合致する対戦履歴の一覧
	 */
	List<MatchResultRequest> selectHistoryRows(@Param("userId") Long userId, @Param("gameTypeId") Integer gameTypeId);

}