package jp.co.sfrontier.ss3.game.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MatchResultExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table match_result
	 * @mbg.generated  Fri Nov 28 13:20:17 JST 2025
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table match_result
	 * @mbg.generated  Fri Nov 28 13:20:17 JST 2025
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table match_result
	 * @mbg.generated  Fri Nov 28 13:20:17 JST 2025
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table match_result
	 * @mbg.generated  Fri Nov 28 13:20:17 JST 2025
	 */
	public MatchResultExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table match_result
	 * @mbg.generated  Fri Nov 28 13:20:17 JST 2025
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table match_result
	 * @mbg.generated  Fri Nov 28 13:20:17 JST 2025
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table match_result
	 * @mbg.generated  Fri Nov 28 13:20:17 JST 2025
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table match_result
	 * @mbg.generated  Fri Nov 28 13:20:17 JST 2025
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table match_result
	 * @mbg.generated  Fri Nov 28 13:20:17 JST 2025
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table match_result
	 * @mbg.generated  Fri Nov 28 13:20:17 JST 2025
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table match_result
	 * @mbg.generated  Fri Nov 28 13:20:17 JST 2025
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table match_result
	 * @mbg.generated  Fri Nov 28 13:20:17 JST 2025
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table match_result
	 * @mbg.generated  Fri Nov 28 13:20:17 JST 2025
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table match_result
	 * @mbg.generated  Fri Nov 28 13:20:17 JST 2025
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table match_result
	 * @mbg.generated  Fri Nov 28 13:20:17 JST 2025
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMatchResultIdIsNull() {
			addCriterion("match_result_id is null");
			return (Criteria) this;
		}

		public Criteria andMatchResultIdIsNotNull() {
			addCriterion("match_result_id is not null");
			return (Criteria) this;
		}

		public Criteria andMatchResultIdEqualTo(Long value) {
			addCriterion("match_result_id =", value, "matchResultId");
			return (Criteria) this;
		}

		public Criteria andMatchResultIdNotEqualTo(Long value) {
			addCriterion("match_result_id <>", value, "matchResultId");
			return (Criteria) this;
		}

		public Criteria andMatchResultIdGreaterThan(Long value) {
			addCriterion("match_result_id >", value, "matchResultId");
			return (Criteria) this;
		}

		public Criteria andMatchResultIdGreaterThanOrEqualTo(Long value) {
			addCriterion("match_result_id >=", value, "matchResultId");
			return (Criteria) this;
		}

		public Criteria andMatchResultIdLessThan(Long value) {
			addCriterion("match_result_id <", value, "matchResultId");
			return (Criteria) this;
		}

		public Criteria andMatchResultIdLessThanOrEqualTo(Long value) {
			addCriterion("match_result_id <=", value, "matchResultId");
			return (Criteria) this;
		}

		public Criteria andMatchResultIdIn(List<Long> values) {
			addCriterion("match_result_id in", values, "matchResultId");
			return (Criteria) this;
		}

		public Criteria andMatchResultIdNotIn(List<Long> values) {
			addCriterion("match_result_id not in", values, "matchResultId");
			return (Criteria) this;
		}

		public Criteria andMatchResultIdBetween(Long value1, Long value2) {
			addCriterion("match_result_id between", value1, value2, "matchResultId");
			return (Criteria) this;
		}

		public Criteria andMatchResultIdNotBetween(Long value1, Long value2) {
			addCriterion("match_result_id not between", value1, value2, "matchResultId");
			return (Criteria) this;
		}

		public Criteria andAttackerIdIsNull() {
			addCriterion("attacker_id is null");
			return (Criteria) this;
		}

		public Criteria andAttackerIdIsNotNull() {
			addCriterion("attacker_id is not null");
			return (Criteria) this;
		}

		public Criteria andAttackerIdEqualTo(Long value) {
			addCriterion("attacker_id =", value, "attackerId");
			return (Criteria) this;
		}

		public Criteria andAttackerIdNotEqualTo(Long value) {
			addCriterion("attacker_id <>", value, "attackerId");
			return (Criteria) this;
		}

		public Criteria andAttackerIdGreaterThan(Long value) {
			addCriterion("attacker_id >", value, "attackerId");
			return (Criteria) this;
		}

		public Criteria andAttackerIdGreaterThanOrEqualTo(Long value) {
			addCriterion("attacker_id >=", value, "attackerId");
			return (Criteria) this;
		}

		public Criteria andAttackerIdLessThan(Long value) {
			addCriterion("attacker_id <", value, "attackerId");
			return (Criteria) this;
		}

		public Criteria andAttackerIdLessThanOrEqualTo(Long value) {
			addCriterion("attacker_id <=", value, "attackerId");
			return (Criteria) this;
		}

		public Criteria andAttackerIdIn(List<Long> values) {
			addCriterion("attacker_id in", values, "attackerId");
			return (Criteria) this;
		}

		public Criteria andAttackerIdNotIn(List<Long> values) {
			addCriterion("attacker_id not in", values, "attackerId");
			return (Criteria) this;
		}

		public Criteria andAttackerIdBetween(Long value1, Long value2) {
			addCriterion("attacker_id between", value1, value2, "attackerId");
			return (Criteria) this;
		}

		public Criteria andAttackerIdNotBetween(Long value1, Long value2) {
			addCriterion("attacker_id not between", value1, value2, "attackerId");
			return (Criteria) this;
		}

		public Criteria andDefenderIdIsNull() {
			addCriterion("defender_id is null");
			return (Criteria) this;
		}

		public Criteria andDefenderIdIsNotNull() {
			addCriterion("defender_id is not null");
			return (Criteria) this;
		}

		public Criteria andDefenderIdEqualTo(Long value) {
			addCriterion("defender_id =", value, "defenderId");
			return (Criteria) this;
		}

		public Criteria andDefenderIdNotEqualTo(Long value) {
			addCriterion("defender_id <>", value, "defenderId");
			return (Criteria) this;
		}

		public Criteria andDefenderIdGreaterThan(Long value) {
			addCriterion("defender_id >", value, "defenderId");
			return (Criteria) this;
		}

		public Criteria andDefenderIdGreaterThanOrEqualTo(Long value) {
			addCriterion("defender_id >=", value, "defenderId");
			return (Criteria) this;
		}

		public Criteria andDefenderIdLessThan(Long value) {
			addCriterion("defender_id <", value, "defenderId");
			return (Criteria) this;
		}

		public Criteria andDefenderIdLessThanOrEqualTo(Long value) {
			addCriterion("defender_id <=", value, "defenderId");
			return (Criteria) this;
		}

		public Criteria andDefenderIdIn(List<Long> values) {
			addCriterion("defender_id in", values, "defenderId");
			return (Criteria) this;
		}

		public Criteria andDefenderIdNotIn(List<Long> values) {
			addCriterion("defender_id not in", values, "defenderId");
			return (Criteria) this;
		}

		public Criteria andDefenderIdBetween(Long value1, Long value2) {
			addCriterion("defender_id between", value1, value2, "defenderId");
			return (Criteria) this;
		}

		public Criteria andDefenderIdNotBetween(Long value1, Long value2) {
			addCriterion("defender_id not between", value1, value2, "defenderId");
			return (Criteria) this;
		}

		public Criteria andMatchDatetimeIsNull() {
			addCriterion("match_datetime is null");
			return (Criteria) this;
		}

		public Criteria andMatchDatetimeIsNotNull() {
			addCriterion("match_datetime is not null");
			return (Criteria) this;
		}

		public Criteria andMatchDatetimeEqualTo(Date value) {
			addCriterion("match_datetime =", value, "matchDatetime");
			return (Criteria) this;
		}

		public Criteria andMatchDatetimeNotEqualTo(Date value) {
			addCriterion("match_datetime <>", value, "matchDatetime");
			return (Criteria) this;
		}

		public Criteria andMatchDatetimeGreaterThan(Date value) {
			addCriterion("match_datetime >", value, "matchDatetime");
			return (Criteria) this;
		}

		public Criteria andMatchDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("match_datetime >=", value, "matchDatetime");
			return (Criteria) this;
		}

		public Criteria andMatchDatetimeLessThan(Date value) {
			addCriterion("match_datetime <", value, "matchDatetime");
			return (Criteria) this;
		}

		public Criteria andMatchDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("match_datetime <=", value, "matchDatetime");
			return (Criteria) this;
		}

		public Criteria andMatchDatetimeIn(List<Date> values) {
			addCriterion("match_datetime in", values, "matchDatetime");
			return (Criteria) this;
		}

		public Criteria andMatchDatetimeNotIn(List<Date> values) {
			addCriterion("match_datetime not in", values, "matchDatetime");
			return (Criteria) this;
		}

		public Criteria andMatchDatetimeBetween(Date value1, Date value2) {
			addCriterion("match_datetime between", value1, value2, "matchDatetime");
			return (Criteria) this;
		}

		public Criteria andMatchDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("match_datetime not between", value1, value2, "matchDatetime");
			return (Criteria) this;
		}

		public Criteria andWinnerIdIsNull() {
			addCriterion("winner_id is null");
			return (Criteria) this;
		}

		public Criteria andWinnerIdIsNotNull() {
			addCriterion("winner_id is not null");
			return (Criteria) this;
		}

		public Criteria andWinnerIdEqualTo(Long value) {
			addCriterion("winner_id =", value, "winnerId");
			return (Criteria) this;
		}

		public Criteria andWinnerIdNotEqualTo(Long value) {
			addCriterion("winner_id <>", value, "winnerId");
			return (Criteria) this;
		}

		public Criteria andWinnerIdGreaterThan(Long value) {
			addCriterion("winner_id >", value, "winnerId");
			return (Criteria) this;
		}

		public Criteria andWinnerIdGreaterThanOrEqualTo(Long value) {
			addCriterion("winner_id >=", value, "winnerId");
			return (Criteria) this;
		}

		public Criteria andWinnerIdLessThan(Long value) {
			addCriterion("winner_id <", value, "winnerId");
			return (Criteria) this;
		}

		public Criteria andWinnerIdLessThanOrEqualTo(Long value) {
			addCriterion("winner_id <=", value, "winnerId");
			return (Criteria) this;
		}

		public Criteria andWinnerIdIn(List<Long> values) {
			addCriterion("winner_id in", values, "winnerId");
			return (Criteria) this;
		}

		public Criteria andWinnerIdNotIn(List<Long> values) {
			addCriterion("winner_id not in", values, "winnerId");
			return (Criteria) this;
		}

		public Criteria andWinnerIdBetween(Long value1, Long value2) {
			addCriterion("winner_id between", value1, value2, "winnerId");
			return (Criteria) this;
		}

		public Criteria andWinnerIdNotBetween(Long value1, Long value2) {
			addCriterion("winner_id not between", value1, value2, "winnerId");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtEqualTo(Date value) {
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotEqualTo(Date value) {
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThan(Date value) {
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThan(Date value) {
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIn(List<Date> values) {
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotIn(List<Date> values) {
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtBetween(Date value1, Date value2) {
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNull() {
			addCriterion("updated_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNotNull() {
			addCriterion("updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtEqualTo(Date value) {
			addCriterion("updated_at =", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotEqualTo(Date value) {
			addCriterion("updated_at <>", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThan(Date value) {
			addCriterion("updated_at >", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_at >=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThan(Date value) {
			addCriterion("updated_at <", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
			addCriterion("updated_at <=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIn(List<Date> values) {
			addCriterion("updated_at in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotIn(List<Date> values) {
			addCriterion("updated_at not in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtBetween(Date value1, Date value2) {
			addCriterion("updated_at between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
			addCriterion("updated_at not between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table match_result
	 * @mbg.generated  Fri Nov 28 13:20:17 JST 2025
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table match_result
     *
     * @mbg.generated do_not_delete_during_merge Fri Nov 28 12:55:43 JST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}