package jp.co.sfrontier.ss3.game.model;

import java.util.Date;

import jakarta.annotation.Generated;

public class MatchResult {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GAME.MATCH_RESULT.MATCH_RESULT_ID
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.match_result_id")
	private Long matchResultId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GAME.MATCH_RESULT.ATTACKER_ID
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.attacker_id")
	private Long attackerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GAME.MATCH_RESULT.DEFENDER_ID
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.defender_id")
	private Long defenderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GAME.MATCH_RESULT.GAME_ID
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	private Long gameId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GAME.MATCH_RESULT.MATCH_DATETIME
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.match_datetime")
	private Date matchDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GAME.MATCH_RESULT.JUDGE
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	private Integer judge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GAME.MATCH_RESULT.CREATED_AT
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.created_at")
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GAME.MATCH_RESULT.UPDATED_AT
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.updated_at")
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GAME.MATCH_RESULT.VERSION
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.version")
	private Integer version;

	/**
	 * アタッカーが出した方向
	 */
	private Integer attackerDirection;

	/**
	 * ディフェンダーが出した方向
	 */
	private Integer defenderDirection;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GAME.MATCH_RESULT.MATCH_RESULT_ID
	 * @return  the value of GAME.MATCH_RESULT.MATCH_RESULT_ID
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.match_result_id")
	public Long getMatchResultId() {
		return matchResultId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GAME.MATCH_RESULT.MATCH_RESULT_ID
	 * @param matchResultId  the value for GAME.MATCH_RESULT.MATCH_RESULT_ID
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.match_result_id")
	public void setMatchResultId(Long matchResultId) {
		this.matchResultId = matchResultId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GAME.MATCH_RESULT.ATTACKER_ID
	 * @return  the value of GAME.MATCH_RESULT.ATTACKER_ID
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.attacker_id")
	public Long getAttackerId() {
		return attackerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GAME.MATCH_RESULT.ATTACKER_ID
	 * @param attackerId  the value for GAME.MATCH_RESULT.ATTACKER_ID
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.attacker_id")
	public void setAttackerId(Long attackerId) {
		this.attackerId = attackerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GAME.MATCH_RESULT.DEFENDER_ID
	 * @return  the value of GAME.MATCH_RESULT.DEFENDER_ID
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.defender_id")
	public Long getDefenderId() {
		return defenderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GAME.MATCH_RESULT.DEFENDER_ID
	 * @param defenderId  the value for GAME.MATCH_RESULT.DEFENDER_ID
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.defender_id")
	public void setDefenderId(Long defenderId) {
		this.defenderId = defenderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GAME.MATCH_RESULT.GAME_ID
	 * @return  the value of GAME.MATCH_RESULT.GAME_ID
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	public Long getGameId() {
		return gameId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GAME.MATCH_RESULT.GAME_ID
	 * @param gameId  the value for GAME.MATCH_RESULT.GAME_ID
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	public void setGameId(Long gameId) {
		this.gameId = gameId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GAME.MATCH_RESULT.MATCH_DATETIME
	 * @return  the value of GAME.MATCH_RESULT.MATCH_DATETIME
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.match_datetime")
	public Date getMatchDatetime() {
		return matchDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GAME.MATCH_RESULT.MATCH_DATETIME
	 * @param matchDatetime  the value for GAME.MATCH_RESULT.MATCH_DATETIME
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.match_datetime")
	public void setMatchDatetime(Date matchDatetime) {
		this.matchDatetime = matchDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GAME.MATCH_RESULT.JUDGE
	 * @return  the value of GAME.MATCH_RESULT.JUDGE
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	public Integer getJudge() {
		return judge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GAME.MATCH_RESULT.JUDGE
	 * @param judge  the value for GAME.MATCH_RESULT.JUDGE
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	public void setJudge(Integer judge) {
		this.judge = judge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GAME.MATCH_RESULT.CREATED_AT
	 * @return  the value of GAME.MATCH_RESULT.CREATED_AT
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.created_at")
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GAME.MATCH_RESULT.CREATED_AT
	 * @param createdAt  the value for GAME.MATCH_RESULT.CREATED_AT
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.created_at")
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GAME.MATCH_RESULT.UPDATED_AT
	 * @return  the value of GAME.MATCH_RESULT.UPDATED_AT
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.updated_at")
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GAME.MATCH_RESULT.UPDATED_AT
	 * @param updatedAt  the value for GAME.MATCH_RESULT.UPDATED_AT
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.updated_at")
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GAME.MATCH_RESULT.VERSION
	 * @return  the value of GAME.MATCH_RESULT.VERSION
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.version")
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GAME.MATCH_RESULT.VERSION
	 * @param version  the value for GAME.MATCH_RESULT.VERSION
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2025-11-28T12:19:05.8969191+09:00", comments = "Source field: match_result.version")
	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getAttackerDirection() {
		return attackerDirection;
	}

	public void setAttackerDirection(Integer attackerDirection) {
		this.attackerDirection = attackerDirection;
	}

	public Integer getDefenderDirection() {
		return defenderDirection;
	}

	public void setDefenderDirection(Integer defenderDirection) {
		this.defenderDirection = defenderDirection;
	}
}